version: "2.1"
services:
  hammond:
    image: akhilrex/hammond
    container_name: hammond
    environment:
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - hammond_config:/config
      - hammond_assets:/assets
    ports:
      - 3001:3000
    restart: unless-stopped
volumes:
  hammond_config:
  hammond_assets:
